# Default values for web-app-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

image:
  repository: poznaninlp/otus_homework
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""
labels:
  app: web-app
  version: "1.2.8"

nameOverride: ""
fullnameOverride: ""

service:
  type: NodePort
  port: 9000

ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: arch.homework
      paths:
        - path: /otusapp/poznanin/(.*)
          pathType: Prefix
        - path: /(health)
          pathType: Prefix


externalPostgresql:
  postgresqlUrl: "jdbc:postgresql://postgres:5432/otus_msa_dz"
  postgresqlUsername: postgres
  postgresqlPassword: postgres

