apiVersion: v1
kind: ConfigMap
metadata:
  name: web-app-config
data:
  OTUS_MSA_DZ_DB_URL: {{ printf "%s" .Values.externalPostgresql.postgresqlUrl | quote }}
  OTUS_MSA_DZ_SERVER_PORT: "8000"

---
apiVersion: v1
kind: Secret
metadata:
  name: web-app-secret
type: Opaque
data:
  OTUS_MSA_DZ_DB_USER: {{ printf "%s" .Values.externalPostgresql.postgresqlUsername| b64enc | quote }}
  OTUS_MSA_DZ_DB_USER_PASSWORD: {{ printf "%s" .Values.externalPostgresql.postgresqlPassword| b64enc | quote }}