// Auto-generated by the postman-to-k6 converter

import "./libs/shim/core.js";
import "./libs/shim/urijs.js";

export let options = { maxRedirects: 4 };

const Request = Symbol.for("request");
postman[Symbol.for("initial")]({
  options,
  collection: {
    BASE_URL: "http://localhost:8080/"
  }
});

export default function() {
  postman[Request]({
    name: "Get Users",
    id: "020ee0c4-4cd0-4d21-aa9e-892a50a790eb",
    method: "GET",
    address: "{{BASE_URL}}api/v1/user/"
  });

  postman[Request]({
    name: "Create User",
    id: "d98e24e7-0dbc-4aa6-98c6-56da016319d2",
    method: "POST",
    address: "{{BASE_URL}}api/v1/user/",
    data:
      '{\r\n  "id": "d46faa86-b816-4c50-82cf-7b25d48ca9f6",\r\n  "name": "Петр",\r\n  "firstName": "Петрович",\r\n  "lastName": "Петров",\r\n  "mail": "pp.petrov@arch.homework",\r\n  "phone": "+79991111111"\r\n}'
  });

  postman[Request]({
    name: "Update User",
    id: "5f54adf3-f346-4cb3-97c4-badee4e2dc9a",
    method: "PUT",
    address: "{{BASE_URL}}api/v1/user/d46faa86-b816-4c50-82cf-7b25d48ca9f6",
    data:
      '{\r\n  "id": "d46faa86-b816-4c50-82cf-7b25d48ca9f6",\r\n  "name": "Петр 2",\r\n  "firstName": "Петрович",\r\n  "lastName": "Петров",\r\n  "mail": "pp.petrov@arch.homework",\r\n  "phone": "+79991111111"\r\n}'
  });

  postman[Request]({
    name: "Get User",
    id: "68a36457-5336-4931-bf33-bdbbe168d23f",
    method: "GET",
    address: "{{BASE_URL}}api/v1/user/d46faa86-b816-4c50-82cf-7b25d48ca9f6"
  });

  postman[Request]({
    name: "Delete User",
    id: "a8e0d5ec-99b6-459e-aa5a-c286330cd973",
    method: "DELETE",
    address: "{{BASE_URL}}api/v1/user/d46faa86-b816-4c50-82cf-7b25d48ca9f6"
  });
}
